#!/usr/bin/env php
<?php
/**
 * Part of Windwalker project.
 *
 * @copyright  Copyright (C) 2016 LYRASOFT. All rights reserved.
 * @license    GNU General Public License version 2 or later.
 */

$autoload = __DIR__ . '/vendor/autoload.php';

if (!is_file($autoload)) {
    exit('Please run `composer install` First.');
}

include $autoload;

include_once __DIR__ . '/etc/define.php';

include __DIR__ . '/vendor/windwalker/core/bin/windwalker.php';
